apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-alertmanager-wechatrobot-webhook
    version: v1
  name: go-alertmanager-wechatrobot-webhook
  namespace: kubesphere-monitoring-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: go-alertmanager-wechatrobot-webhook
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-alertmanager-wechatrobot-webhook
        version: v1
    spec:
      containers:
      - env:
        - name: ROBOT_TOKEN
          value: xxxxxxxxxxxxxxxxxxxxxxxxx
        image: registry.cn-hangzhou.aliyuncs.com/zuoyang/go-alertmanager-wechatrobot-webhook:zuoyang-2024.03.06-15.48.10
        imagePullPolicy: Always
        name: go-alertmanager-wechatrobot-webhook
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: jj-images
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-alertmanager-wechatrobot-webhook
  name: go-alertmanager-wechatrobot-webhook-svc
  namespace: kubesphere-monitoring-system
spec:
  clusterIP: 10.233.33.22
  clusterIPs:
  - 10.233.33.22
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30286
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-alertmanager-wechatrobot-webhook
  sessionAffinity: None
  type: NodePort