apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: go-alertmanager-webhook-weixin  
  namespace: kubesphere-monitoring-system  
  labels:  
    app: go-alertmanager-webhook-weixin  
    version: v1  
spec:  
  replicas: 1  
  selector:  
    matchLabels:  
      app: go-alertmanager-webhook-weixin  
      version: v1  
  template:  
    metadata:  
      labels:  
        app: go-alertmanager-webhook-weixin  
        version: v1  
    spec:  
      imagePullSecrets:  
        - name: jj-images  
      containers:  
        - name: go-alertmanager-webhook-weixin  
          image: registry.cn-hangzhou.aliyuncs.com/zuoyang/alertmanager-webhok-wx-py:v2024.02.29-10.54.03  
          imagePullPolicy: Always  
          env:  
            - name: ROBOT_TOKEN  
              value: "577aa9e0-816f-49f4-80d7-40e0237c77c5"  
          resources:  
            limits:  
              cpu: 200m  
              memory: 256Mi  
            requests:  
              cpu: 100m  
              memory: 128Mi  
          terminationMessagePolicy: File  
      tolerations:  
        - key: node.kubernetes.io/not-ready  
          operator: Exists  
          effect: NoExecute  
          tolerationSeconds: 300  
        - key: node.kubernetes.io/unreachable  
          operator: Exists  
          effect: NoExecute  
          tolerationSeconds: 300
---
apiVersion: v1  
kind: Service  
metadata:  
  name: go-alertmanager-webhook-weixin-svc  
  namespace: kubesphere-monitoring-system  
  labels:  
    app: go-alertmanager-webhook-weixin  
spec:  
  selector:  
    app: go-alertmanager-webhook-weixin  
  ports:  
    - name: http  
      protocol: TCP  
      port: 8080  
  clusterIP: 10.233.33.22
